name: Build and push docker image

on:
  push:
    branches: [main]

jobs:
  build-and-push-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          echo "${{vars.ENV_FILE}}" > .env
          cat .env
          ls -la
          # docker build -t netflix_backend:latest .
