name: Build and push docker image

on:
  push:
    branches: [main]

jobs:
  build-and-push-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out the repo
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          if [[ -n "${{ secrets.ENV_FILE }}" ]]; then
            echo "Secret is present ✅"
          else
            echo "Secret missing ❌"
          fi
          # docker build -t netflix_backend:latest .
